import Head from 'next/head'
import Footer from '../components/footer/Footer'
import Header from '../components/header/Header'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <>
    <Header />
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.main_banner}>
            <div className={styles.main_banner_content}>
              <div className={styles.main_banner_text}>
                  <h1>Treinamento do Sistema</h1>
                  <h2>Para iniciantes começarem a operar o nosso sistema totalmente treinados e prontos para sua jornada.</h2>
              </div>
              <div className={styles.main_image}>
                <img src="/home_mainbanner-removebg-preview.png" />
              </div>
            </div>
            <div className={styles.search_bar}>
              <input type="text" placeholder="Digite aqui a palavra chave" />
              <input type="submit" value="Pesquisar" />
            </div>
        </div>
        <div className={styles.video_showroom}>
            <h3>Aqui, nosso treinamento é totalmente online,  fácil e  descomplicado.</h3>
            <img src="/video_showroom.jpeg" />
        </div>
        <div className={styles.formation_way}>
          <h4>Trilha de Formação</h4>
          <div className={styles.formation_way_content_inner}>
            <div className={styles.system_names}>
              <img src="/sap_logo.png" />
              <h5>Sistema SAP</h5>
              <p>Portal de compras <br/>
                Cadastro Fornecedores <br/>
                Portal de compras <br/>
                Cadastro Fornecedores
              </p>
            </div>
            <div className={styles.system_names}>
              <img src="/sap_logo.png" />
              <h5>Dados</h5>
              <p>Relatorios compras<br/>
              Analitics<br/>
              Orçamentos compras<br/>
              Orçamentos imoveis<br/>
              Compliance<br/>
              Monitor de processos
              </p>
            </div>
            <div className={styles.system_names}>
              <img src="/sap_logo.png" />
              <h5>Documentos</h5>
              <p>Assinatura de contratos<br/>
                Gestão de contratos<br/>
                Normas de compras<br/>
                Regras de processos</p>
            </div>
            <div className={styles.system_names}>
              <img src="/sap_logo.png" />
              <h5>Processos</h5>
              <p>Avaliação fornecedores<br/>
                Dados fornecedores<br/>
                Sustentabilidade Ikus<br/>
                Avaliação de fornecedores<br/>
                Cadastro de fornecedores</p>
            </div>
          </div>
        </div>
      </main>
      <Footer />

    </div>
    </>
  )
}
